[workspace]
members = ["examples/tauri-app/src-tauri"]
resolver = "2"

[workspace.package]
authors = ["Flight Science"]
license = "MIT"
edition = "2024"
repository = "https://github.com/fltsci/tauri-plugin-tracing"

[package]
name = "tauri-plugin-tracing"
version = "0.2.0-canary.0"
description = "Use the tracing crate in your Tauri app"
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
links = "tauri-plugin-tracing"
exclude = ["/examples", "/dist-js", "/guest-js", "/node_modules"]
publish = ["kellnr"]

[package.metadata.platforms.support]
windows = { level = "unknown", notes = "" }
linux = { level = "unknown", notes = "" }
macos = { level = "full", notes = "" }
android = { level = "unknown", notes = "" }
ios = { level = "unknown", notes = "" }

[build-dependencies]
tauri-plugin = { version = "2.5.1", features = ["build"] }

[dependencies]
serde = { version = "1.0.228", default-features = false }
tauri = { version = "2.9.1", default-features = false }
thiserror = { version = "2.0.17", default-features = false }
serde_repr = "0.1.20"
tracing = { version = "0.1.41" }
time = { version = "0.3.44", default-features = false }
tracing-appender = "0.2.3"
tracing-core = "0.1.34"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
colored = { version = "3.0.0", optional = true }
specta = { version = "=2.0.0-rc.22", features = ["derive"], optional = true }
ahash = { version = "0.8.12", features = ["serde"], optional = true }
compact_str = { version = "0.9.0", features = ["serde"], optional = true }

# default to small, optimized release binaries
[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"

[features]
default = []
colored = ["dep:colored", "tracing-subscriber/ansi"]
specta = ["dep:specta"]
timing = ["dep:compact_str", "dep:ahash"]
