[workspace]
members = ["examples/tauri-app/src-tauri"]
resolver = "2"

[package]
name = "tauri-plugin-tracing"
version = "0.1.1"
authors = ["Flight Science"]
description = "Use the tracing crate in your Tauri app"
license = "MIT"
license-file = "LICENSE.md"
edition = "2024"
exclude = ["/examples", "/dist-js", "/guest-js", "/node_modules"]
links = "tauri-plugin-tracing"
repository = "https://github.com/fltsci/tauri-plugin-tracing"
publish = ["kellnr"]

[build-dependencies]
tauri-plugin = { version = "2.2.0", features = ["build"] }

[dependencies]
serde = { version = "1.0.217", default-features = false }
tauri = { version = "2.5.1", default-features = false }
thiserror = { version = "2.0.12", default-features = false }
serde_repr = "0.1.20"
tracing = { version = "0.1.41", default-features = false }
time = { version = "0.3.41", default-features = false }
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.19", default-features = false }
colored = "3.0.0"

# default to small, optimized release binaries
[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"
