name: version or publish

on:
  push:
    branches:
      - main

permissions:
  # required for npm provenance
  id-token: write
  # required to create the GitHub Release
  contents: write
  # required for creating the Version Packages Release
  pull-requests: write
  # required to create lables on the repository
  issues: write

jobs:
  version-or-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 65
    outputs:
      change: ${{ steps.covector.outputs.change }}
      commandRan: ${{ steps.covector.outputs.commandRan }}
      successfulPublish: ${{ steps.covector.outputs.successfulPublish }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required for use of git history

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - run: pnpm i --frozen-lockfile

      - name: get release channel
        id: release-channel
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: 'string'
          script: |
            const script = require('./.scripts/ci/get-release-channel.cjs');
            return await script({github, context});

      - name: cargo login
        run: cargo login ${{ secrets.CRATES_IO_PROXY_TOKEN }} --registry kellnr

      - name: git config
        run: |
          git config --global user.name "${{ github.event.pusher.name }}"
          git config --global user.email "${{ github.event.pusher.email }}"

      - name: Setup target dir on /mnt
        # This directory has a larger partition size
        run: |
          sudo mkdir /mnt/target
          WORKSPACE_OWNER="$(stat -c '%U:%G' "${GITHUB_WORKSPACE}")"
          sudo chown -R "${WORKSPACE_OWNER}" /mnt/target

      - name: covector version or publish (publish when no change files present)
        uses: jbolda/covector/packages/action@covector-v0
        id: covector
        env:
          CARGO_TARGET_DIR: /mnt/target
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: 'version-or-publish'
          createRelease: true
          recognizeContributors: true
          identifier: ${{ steps.release-channel.outputs.result }}

      - name: 'ran covector ${{ steps.covector.outputs.commandRan }}'
        run: echo "ran command 'covector ${{ steps.covector.outputs.commandRan }}'"

      - name: Sync Cargo.lock
        if: steps.covector.outputs.commandRan == 'version'
        run: cargo tree --depth 0

      - name: Create Pull Request With Versions Bumped
        id: cpr
        uses: peter-evans/create-pull-request@dd2324fc52d5d43c699a5636bcf19fceaa70c284 # 7.0.7
        if: steps.covector.outputs.commandRan == 'version'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: 'Publish New Versions'
          sign-commits: true
          commit-message: 'publish new versions'
          labels: 'version updates'
          branch: 'release'
          body: ${{ steps.covector.outputs.change }}
